// Suggested biases as answers (sets of 4 options per "bias" question)
const BIAS = {
  conf:  {l:"🔁 Confirmation bias", s:"we prefer what confirms our ideas"},
  halo:  {l:"⭐ Halo effect", s:"competent here = believed everywhere"},
  emo:   {l:"💓 Emotional bias", s:"emotion grabs our attention"},
  popu:  {l:"📣 Popularity bias", s:"“everyone believes it!”"},
  heur:  {l:"⚡ Heuristic", s:"a too-fast conclusion, without all the facts"},
  surv:  {l:"✈️ Survivorship bias", s:"we only see those who “survived”"},
  cadr:  {l:"🖼️ Framing effect", s:"the presentation shapes perception"},
  ancr:  {l:"⚓ Anchoring effect", s:"the 1st number becomes the reference point"},
  auto:  {l:"🎓 Authority bias", s:"“an expert / a lab coat said it”"},
  disp:  {l:"📰 Availability bias", s:"what comes quickly to mind seems frequent"},
  caus:  {l:"🔗 Correlation ≠ causation", s:"linked ≠ one causes the other"},
  nega:  {l:"⚠️ Negativity bias", s:"the negative sticks more than the positive"},
  retro: {l:"🕰️ Hindsight bias", s:"“I knew it all along!”"},
  barn:  {l:"♈ Barnum effect", s:"“this vague profile is totally me!”"},
};

// type "piege": riddle with a false intuitive answer. type "biais": identify the bias (a + 3 distractors)
const ITEMS = [
  {type:"piege", t:"A bat and a ball cost €1.10 together. The bat costs €1 MORE than the ball. How much does the ball cost?",
   opts:["10 cents","5 cents","1 euro","15 cents"], a:1,
   e:"Your intuition shouts “10 cents”! But then the bat would cost €1.10 and the total would be €1.20. The correct answer is <b>5 cents</b> (bat: €1.05). This is the classic riddle of the <b>two systems of thinking</b>: intuition answers fast and wrong, analysis answers slowly and correctly."},
  {type:"piege", t:"If 5 machines take 5 minutes to make 5 objects, how long do 100 machines take to make 100 objects?",
   opts:["100 minutes","20 minutes","5 minutes","50 minutes"], a:2,
   e:"Intuition says “100”! But each machine takes 5 minutes to make ITS object. So 100 machines make 100 objects in… <b>5 minutes</b>. Another trap set for intuitive thinking."},
  {type:"piege", t:"On a lake, lily pads double in area every day. They cover the whole lake in 48 days. In how many days do they cover HALF the lake?",
   opts:["24 days","47 days","12 days","36 days"], a:1,
   e:"“24” seems obvious… but if the area DOUBLES every day, half the lake is reached <b>the day before</b> the whole lake: on day <b>47</b>. Taking 2 seconds to think changes everything."},
  {type:"piege", t:"In Moon photos, the American flag seems to be waving… even though there is no wind on the Moon. Conclusion?",
   opts:["We never went to the Moon","The flag is held up by a metal rod","There is a little wind on the Moon","The photo was edited"], a:1,
   e:"“Waving flag + no wind = lie”: that is a too-fast reasoning shortcut, a <b>heuristic</b>. If you look more closely at the photo, you can see a <b>metal rod</b> holding up the fabric. Before shouting conspiracy, look for the simple explanation."},
  {type:"biais", t:"Kevin is convinced that women are bad drivers. When he sees a statistic showing that men have more serious accidents, he replies: “those figures are rigged” — but he clearly remembers ONE video of a woman parking badly.",
   a:"conf", opts:["halo","popu","surv"],
   e:"<b>Confirmation bias</b>: we accept without checking what confirms our ideas, and reject (or forget) what contradicts them. It is one of the brain's biggest traps — and one of the gateways into conspiracy theories."},
  {type:"biais", t:"An Olympic judo champion advertises a car. Many people think: “if he recommends it, it must be a good car.”",
   a:"halo", opts:["popu","emo","heur"],
   e:"The <b>halo effect</b>: we transfer someone's skill (judo!) to a field that has nothing to do with it (cars). Celebrity advertising relies entirely on this bias."},
  {type:"biais", t:"On social media, a heartbreaking photo of a child and his dog in ruins gets millions of shares. It was generated by AI.",
   a:"emo", opts:["conf","cadr","popu"],
   e:"<b>Emotional bias</b>: information that moves us grabs our attention and spreads faster — whether it is true or false. That is why the most viral fake news plays on anger, fear or tenderness. Breathe before sharing!"},
  {type:"biais", t:"“Millions of people use this health tip, so it must work!”",
   a:"popu", opts:["surv","halo","conf"],
   e:"<b>Popularity bias</b>: the number of believers proves nothing. Millions of people long believed that Earth was at the centre of the universe. Truth is not measured in likes."},
  {type:"biais", t:"During the war, engineers study the planes that RETURN to base to decide where to reinforce them. They have bullet holes in the wings: people want to reinforce the wings. Statistician Abraham Wald says: “No! Reinforce the places where there are NO bullet holes.”",
   a:"surv", opts:["heur","conf","cadr"],
   e:"<b>Survivorship bias</b>: the planes hit elsewhere never came back! People only saw the “survivors”. Same trap when someone says “my grandfather smoked his whole life and lived to 95”: we do not see all those who died earlier."},
  {type:"biais", t:"“My great-grandmother smoked a pack a day until she was 96, so tobacco can't be that dangerous.”",
   a:"surv", opts:["conf","heur","popu"],
   e:"Survivorship bias again: people cite the exceptional case that “survived”, while forgetting the millions of smokers who died early and never get to testify. A single case does not disprove a statistic."},
  {type:"biais", t:"The same survey produces two headlines: “64% of French people keep their Christmas budget” or “more than one French person in three must cut their Christmas budget”. Depending on the headline, you do not feel the same thing at all.",
   a:"cadr", opts:["emo","conf","heur"],
   e:"The <b>framing effect</b>: the SAME information, presented differently, changes our perception. The glass half full or half empty. No lie — just a chosen angle."},
  {type:"biais", t:"“Schizophrenia means having several personalities”: lots of people are sure of it… because they have seen it in films and TV shows.",
   a:"heur", opts:["halo","popu","conf"],
   e:"A <b>too-fast conclusion</b> based on what comes to mind (fiction!) is a <b>heuristic</b>. Schizophrenia has nothing to do with multiple personalities. Hence the key question: <b>“where did I get what I believe?”</b>"},
  {type:"biais", t:"A speaker talks about psychology for 1 hour 30 minutes to a class. At the end, he asks: “by the way… why did you believe me? I never told you I was a psychologist.” Nobody had checked.",
   a:"heur", opts:["popu","emo","cadr"],
   e:"They trusted him through a <b>shortcut</b>: he was invited by the school, he spoke well, so “he must be legitimate”. That is often true… but you need to ask: <b>is this person competent on THIS topic?</b> Many people speak in the media outside their field."},
  {type:"piege", t:"In your opinion, what is the best habit BEFORE sharing information on social media?",
   opts:["Check that it has lots of likes","Count to 2 and ask whether it is reliable","Share it quickly to inform others","Check that it comes from a trusted friend"], a:1,
   e:"<b>Count to 2</b>: a simple breath that switches you from intuitive mode to analytical mode. “Why do I want to share this? Is it flattering my confirmation bias? Too good to be true?” 2 seconds are enough — and they change everything."},

  // ===== 30 additional questions =====
  {type:"piege", t:"In a running race, you overtake the runner in 2nd place. You are now…",
   opts:["1st","2nd","3rd","It depends"], a:1,
   e:"By overtaking the 2nd-place runner, you take THEIR place: you are <b>2nd</b>, not 1st! Intuition reflexively shouts “1st”. Count to 2 and everything becomes clear."},
  {type:"piege", t:"How many animals of each species did Moses take onto his ark?",
   opts:["Two","Seven","None","One pair"], a:2,
   e:"<b>None</b>: it was not Moses, but <b>Noah</b>! Your brain reads too quickly and misses the error hidden in the sentence — this is called the “Moses illusion”. Always reread the question."},
  {type:"piege", t:"You are prescribed 3 pills, one every 30 minutes. After how much time will you have taken the last one?",
   opts:["1h30","1h","45 min","30 min"], a:1,
   e:"1st at 0 min, 2nd at 30 min, 3rd at 60 min: <b>1 hour</b> passes. Intuition does 3×30 = 1h30 without noticing that the first pill involves no waiting time."},
  {type:"piege", t:"How many months of the year have (at least) 28 days?",
   opts:["1","2","12","11"], a:2,
   e:"<b>All 12 months</b> have at least 28 days! Intuition immediately thinks “February” and answers 1 without rereading the question."},
  {type:"piege", t:"A drawer contains 10 black socks and 10 blue socks mixed together. In total darkness, how many must you take out to be SURE you have 2 socks of the same colour?",
   opts:["2","3","11","21"], a:1,
   e:"<b>3 are enough</b>: with only 2 colours, by the 3rd sock at least two must be the same. Intuition overestimates (“11!”) out of excess caution."},
  {type:"piege", t:"A snail climbs a 10 m well. During the day it climbs 3 m; at night it slips down 2 m. In how many days does it get out of the well?",
   opts:["10 days","8 days","5 days","20 days"], a:1,
   e:"It gains 1 m net per day… but on the 8th day, starting from 7 m, it climbs 3 m and reaches 10 m: it is out before slipping back! Answer: <b>8 days</b>, not 10."},
  {type:"piege", t:"One plane leaves a long white trail in the sky, another almost none. For some people, this proves we are being “sprayed” with products. The most likely explanation?",
   opts:["We are being poisoned in secret","Condensation, which varies with altitude, temperature and humidity","Some planes pollute more","It is chemical smoke"], a:1,
   e:"“Strange trail = conspiracy” is a too-fast shortcut. A normal explanation exists: <b>condensation</b> depends on temperature and humidity at flight altitude. Look for the simple explanation before the extraordinary one."},
  {type:"piege", t:"You read shocking information shared by someone close to you. What is the BEST reflex?",
   opts:["Share it quickly to warn everyone","Trace it back to the original source before believing it","Believe it, because it comes from someone close","Check that it has lots of shares"], a:1,
   e:"<b>Trace it back to the source</b>: who said this originally? when? with what evidence? A well-meaning friend can pass on false information, and the number of shares proves nothing. Count to 2, then verify."},

  {type:"biais", t:"An ad proclaims: “100% of our winners tried their luck! What if it were you?”",
   a:"surv", opts:["caus","popu","emo"],
   e:"<b>Survivorship bias</b>: you are only shown the winners. Of course they played… just like the millions of invisible losers! Trying your luck does not “cause” winning."},
  {type:"biais", t:"“Steve Jobs and Bill Gates dropped out of school and became billionaires: proof that school is useless for success.”",
   a:"surv", opts:["popu","caus","halo"],
   e:"<b>Survivorship bias</b>: people cite 2 famous successes while forgetting the millions of dropouts who did NOT succeed and whom nobody talks about. Exceptions do not make the rule."},
  {type:"biais", t:"You are first asked “is the Eiffel Tower taller or shorter than 1000 m?”, then asked to estimate its height. You overestimate it by a lot (it is 330 m tall).",
   a:"ancr", opts:["disp","cadr","heur"],
   e:"The <b>anchoring effect</b>: the “1000” heard just before becomes a reference point that pulls your estimate upward, even though it is absurd. Crossed-out prices in shops exploit exactly this."},
  {type:"biais", t:"The salesperson first announces €18,000 for the car, then “makes a gesture” at €15,000. Suddenly you think it is a great deal.",
   a:"ancr", opts:["cadr","popu","auto"],
   e:"The <b>anchoring effect</b>: the first price (€18,000) serves as a reference and makes €15,000 seem “advantageous”, even if the car is worth €12,000. Set YOUR reference price before negotiating."},
  {type:"biais", t:"A toothpaste label says: “Recommended by dentists”. You buy it without hesitation.",
   a:"auto", opts:["halo","popu","conf"],
   e:"<b>Authority bias</b>: a title or a lab coat is enough to convince us, without proof or details (which dentists? how many? paid?). An authority can be wrong — ask for proof, not the label."},
  {type:"biais", t:"In a video, a man in a white coat claims that a remedy “cleanses toxins”. No name, no verifiable diploma, but the coat is enough to convince the comments.",
   a:"auto", opts:["barn","halo","emo"],
   e:"<b>Authority bias</b>: an expert costume (lab coat, TV studio, confident tone) inspires trust without any real proof. The symbol is not competence."},
  {type:"biais", t:"After a report about a plane crash, Léa cancels her flight and prefers to drive 1000 km, “much safer”.",
   a:"disp", opts:["emo","nega","conf"],
   e:"<b>Availability bias</b>: the crash, striking and recent, comes easily to mind, so it seems frequent. Statistically, however, the car is much more dangerous than the plane."},
  {type:"biais", t:"We observe that the more ice cream is sold, the more drownings occur. Should we ban ice cream to save lives?",
   a:"caus", opts:["conf","surv","popu"],
   e:"<b>Correlation is not causation</b>: it is <b>summer</b> (heat) that makes both rise at the same time. Ice cream does not cause drownings. Always look for the hidden cause."},
  {type:"biais", t:"“Students who have a smartphone have worse grades: phones make you stupid.”",
   a:"caus", opts:["conf","nega","surv"],
   e:"<b>Correlation ≠ causation</b>: other factors (sleep, background, how the phone is used) can explain both. An observed link does not say what causes what."},
  {type:"biais", t:"TV news strings together crimes, dramas and disasters. Many people conclude that “everything is getting worse and worse in the world”.",
   a:"nega", opts:["disp","cadr","popu"],
   e:"<b>Negativity bias</b>: misfortune grabs more attention and spreads more than quiet progress. It is not necessarily that everything is getting worse — it is that the negative makes more noise."},
  {type:"biais", t:"After a cryptocurrency collapses, your uncle declares: “It was obvious it was going to crash, I always said so!” Yet he had invested in it.",
   a:"retro", opts:["conf","heur","popu"],
   e:"<b>Hindsight bias</b>: once the outcome is known, we are convinced we “knew it all along”. The future seems obvious… only after the fact."},
  {type:"biais", t:"After the team's defeat, supporters shout: “We knew it from the start, this coach was useless!” Before the match, they adored him.",
   a:"retro", opts:["popu","conf","emo"],
   e:"<b>Hindsight bias</b>: the known result rewrites our memories. We reconstruct a past where “everything was predictable”."},
  {type:"biais", t:"“You are sociable, but you also need moments of solitude; you sometimes doubt your choices.” Marie feels that her horoscope is “incredibly accurate”.",
   a:"barn", opts:["conf","emo","auto"],
   e:"The <b>Barnum effect</b>: the description is so vague that it fits almost everyone. Ask yourself: “could this apply to anyone?” That is the whole trick behind horoscopes and fortune-tellers."},
  {type:"biais", t:"An online test reveals your “unique profile”. The description feels perfectly like you… and your friend gets another result but finds it just as accurate.",
   a:"barn", opts:["conf","auto","heur"],
   e:"The <b>Barnum effect</b>: these profiles are vague enough to suit everyone. The feeling “that is so me!” is not proof of reliability."},
  {type:"biais", t:"Convinced that a food is dangerous, Tom searches the internet for “food X danger” and finds lots of results that prove him right.",
   a:"conf", opts:["disp","popu","auto"],
   e:"<b>Confirmation bias</b>: by searching “X danger”, he only finds what confirms his fear. If he had searched “X benefits”, he would have found the opposite. The query already shapes the answer."},
  {type:"biais", t:"During a debate, you remember all the arguments from “your side” and immediately forget the other side's arguments, which you find “stupid”.",
   a:"conf", opts:["emo","halo","retro"],
   e:"<b>Confirmation bias</b>: we remember what suits us and discard the rest. To counter it: try to state the strongest opposing argument honestly."},
  {type:"biais", t:"In an interview, a very good-looking and smiling candidate is judged more competent and more honest than the others before their skills have even been tested.",
   a:"halo", opts:["auto","conf","cadr"],
   e:"The <b>halo effect</b>: one visible quality (appearance, smile) spills over onto everything else. Good-looking ≠ competent ≠ honest. Separate appearance from substance."},
  {type:"biais", t:"A product has 10,000 five-star reviews, so Sarah buys it without reading anything: “with that many people, it must be good.”",
   a:"popu", opts:["auto","halo","surv"],
   e:"<b>Popularity bias</b> (social proof): numbers reassure us, but reviews can be bought, filtered or misleading. Quantity is not proof of quality."},
  {type:"biais", t:"An outraged post saying “SHARE quickly before they delete this!!!” makes you want to repost it immediately, without checking the source.",
   a:"emo", opts:["popu","conf","auto"],
   e:"<b>Emotional bias</b>: urgency and outrage short-circuit reflection. The more a message pushes you to react fast, the more you should slow down and verify."},
  {type:"biais", t:"A dietary supplement with a scientific-sounding name, “with patented Garcinia Cambogia extract”, seems serious and effective to you just because of the name.",
   a:"heur", opts:["auto","halo","barn"],
   e:"A <b>heuristic</b>: complicated name = “it sounds scientific” = “it must work”. Classic shortcut. A fancy word proves no effectiveness."},
  {type:"biais", t:"“This operation has a 90% success rate” is much more reassuring than “this operation has a 10% failure rate”, even though it is exactly the same figure.",
   a:"cadr", opts:["emo","ancr","disp"],
   e:"The <b>framing effect</b>: gain or loss, it is the same data, but our feelings and decisions change. Doctors and advertisers choose the angle on purpose."},
  {type:"biais", t:"A steak labelled “80% lean” seems more appetising than the same steak labelled “20% fat”, even though they are strictly identical.",
   a:"cadr", opts:["emo","ancr","popu"],
   e:"The <b>framing effect</b>: the same reality, phrased positively or negatively, does not trigger the same feeling. Rephrase the information the other way to spot the chosen angle."},
];

const QTIME=15; // seconds to answer once the breathing pause has passed
let deck=[],idx=0,score=0,streak=0,best=0,locked=true,timer=null,countdown=null,timeLeft=QTIME,timedOut=0;
const $=id=>document.getElementById(id);
function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}

function startGame(){
  deck=shuffle([...ITEMS]).slice(0,12);
  idx=0;score=0;streak=0;best=0;timedOut=0;
  $("fiches").style.display="none";
  $("intro").style.display="none";
  $("hud").style.display="flex";
  $("game").style.display="block";
  $("qtot").textContent=deck.length;
  renderQ();
}

function renderQ(){
  const it=deck[idx];
  $("qnum").textContent=idx+1;
  $("scase").textContent="Case no. "+String(idx+1).padStart(2,"0");
  $("stxt").textContent=it.t;
  const tag=$("stag");
  if(it.type==="piege"){tag.className="stag piege";tag.textContent="⚡ Trap riddle";}
  else{tag.className="stag biais";tag.textContent="🔍 Which bias is at work?";}
  $("feedback").style.display="none";
  $("nextbtn").style.display="none";
  const ans=$("answers");ans.innerHTML="";
  let choices,correct;
  if(it.type==="piege"){
    choices=it.opts.map((o,i)=>({label:o,sub:"",ok:i===it.a}));
    choices=shuffle(choices);
  } else {
    const pool=[{...BIAS[it.a],ok:true},...it.opts.map(id=>({...BIAS[id],ok:false}))];
    choices=shuffle(pool).map(c=>({label:c.l,sub:c.s,ok:c.ok}));
  }
  choices.forEach(c=>{
    const b=document.createElement("button");
    b.className="abtn locked";
    b.innerHTML=c.label+(c.sub?`<span class="asub">${c.sub}</span>`:"");
    b.dataset.ok=c.ok?"1":"0";
    b.onclick=()=>answer(it,b);
    ans.appendChild(b);
  });
  // Breathing pause: 2-second lock
  locked=true;
  clearInterval(countdown);
  $("timer-wrap").style.display="none";
  const circ=$("breath-circle");
  $("breath").style.visibility="visible";
  circ.textContent="1";
  clearTimeout(timer);
  timer=setTimeout(()=>{circ.textContent="2";},1000);
  setTimeout(()=>{
    if(idx>=deck.length)return;
    locked=false;
    $("breath").style.visibility="hidden";
    document.querySelectorAll(".abtn").forEach(b=>b.classList.remove("locked"));
    startCountdown(it);
  },2000);
}

function startCountdown(it){
  clearInterval(countdown);
  timeLeft=QTIME;
  const wrap=$("timer-wrap"),num=$("timer-num"),fill=$("timer-fill");
  wrap.style.display="flex";
  wrap.classList.remove("timer-low");
  num.textContent=timeLeft;
  fill.style.width="100%";
  countdown=setInterval(()=>{
    timeLeft--;
    num.textContent=Math.max(timeLeft,0);
    fill.style.width=Math.max(timeLeft/QTIME*100,0)+"%";
    if(timeLeft<=5)wrap.classList.add("timer-low");
    if(timeLeft<=0){clearInterval(countdown);timeUp(it);}
  },1000);
}

function timeUp(it){
  locked=true;
  $("timer-wrap").style.display="none";
  document.querySelectorAll(".abtn").forEach(b=>{
    b.disabled=true;b.classList.add("dim");
    if(b.dataset.ok==="1"){b.classList.remove("dim");b.classList.add("good");}
  });
  streak=0;timedOut++;
  $("streak").textContent="";
  $("fb-title").textContent="⏱ Too late! Your System 1 hesitated…";
  const fb=$("feedback");fb.className="ko";fb.style.display="block";
  $("fb-expl").innerHTML="Time is up. Here is the correct answer:<br><br>"+it.e;
  $("nextbtn").textContent=idx===deck.length-1?"See my final result ➜":"Next question ➜";
  $("nextbtn").style.display="block";
  $("nextbtn").scrollIntoView({behavior:"smooth",block:"end"});
  $("nextbtn").focus();
}

function answer(it,btn){
  if(locked)return;
  locked=true;
  clearInterval(countdown);
  $("timer-wrap").style.display="none";
  const ok=btn.dataset.ok==="1";
  document.querySelectorAll(".abtn").forEach(b=>{
    b.disabled=true;b.classList.add("dim");
    if(b.dataset.ok==="1"){b.classList.remove("dim");b.classList.add("good");}
  });
  if(ok){
    streak++;best=Math.max(best,streak);
    const fast=timeLeft>=QTIME-6; // answered correctly AND quickly
    score+=10+(streak>=3?5:0)+(fast?5:0);
    let t;
    if(fast)t="⚡ Fast AND correct — System 1 mastered! (+"+(15+(streak>=3?5:0))+(streak>=3?`, streak of ${streak} 🔥`:"")+")";
    else if(streak>=3)t=`✔ Analytical brain activated! (+15, streak of ${streak} 🔥)`;
    else t="✔ Well done, you kept a cool head! (+10)";
    $("fb-title").textContent=t;
  } else {
    btn.classList.remove("dim");btn.classList.add("bad");
    streak=0;
    $("fb-title").textContent="✘ Your intuition tricked you!";
  }
  $("score").textContent=score;
  $("streak").textContent=streak>=2?`🔥 ${streak}`:"";
  const fb=$("feedback");
  fb.className=ok?"ok":"ko";fb.style.display="block";
  $("fb-expl").innerHTML=it.e;
  $("nextbtn").textContent=idx===deck.length-1?"See my final result ➜":"Next question ➜";
  $("nextbtn").style.display="block";
  $("nextbtn").scrollIntoView({behavior:"smooth",block:"end"});
  $("nextbtn").focus();
}

function nextQ(){
  if(idx===deck.length-1){endGame();return;}
  idx++;renderQ();
  window.scrollTo({top:0,behavior:"smooth"});
}

function endGame(){
  clearInterval(countdown);clearTimeout(timer);
  $("timer-wrap").style.display="none";
  $("game").style.display="none";
  $("nextbtn").style.display="none";
  $("hud").style.display="none";
  $("end").style.display="block";
  $("end-score").textContent=score+" pts";
  const ratio=score/(deck.length*10);
  let title,msg;
  if(ratio>=0.9){title="🏆 Master of metacognition!";msg="Your analytical brain is in charge. You know how to step back from your own thinking — that is exactly what <b>metacognition</b> is.";}
  else if(ratio>=0.6){title="🧠 Good bias hunter!";msg="You already spot most traps. Remember: trust your brain, yes — but know that it sometimes plays tricks on us.";}
  else{title="⚡ Intuition gave you a hard time…";msg="Don't panic: these traps fool almost everyone the first time! Play again, and above all: <b>count to 2</b> before answering.";}
  if(best>=5)msg+="<br><br>Your best streak: <b>"+best+" 🔥</b>";
  if(timedOut>0)msg+="<br><br>⏱ Time-outs: <b>"+timedOut+"</b> — under pressure, keep a cool head: breathe, then decide.";
  msg+="<br><br>💡 <i>“The enemy of knowledge is not ignorance: it is the illusion of knowledge.”</i>";
  $("end-title").textContent=title;
  $("end-msg").innerHTML=msg;
}

// ===== Anti-bias cards =====
const FICHES = [
  {concept:true, icon:"🧠", title:"Your two brains",
   def:"Your mind has two speeds. <b>System 1</b> is fast, automatic and intuitive. <b>System 2</b> is slow, reflective and analytical. System 1 decides almost everything… and it is the one that falls into traps.",
   ex:"€1.10 riddle: you answer “10 cents” without thinking (System 1). The correct answer, 5 cents, requires doing the calculation (System 2).",
   parade:"Count to 2: this small delay gives System 2 time to wake up before answering or sharing."},
  {id:"conf",
   def:"We mainly look for, remember and believe what <b>confirms</b> our ideas — and ignore or minimise what contradicts them.",
   ex:"Kevin remembers ONE woman parking badly, but dismisses the statistics that contradict him as “rigged”.",
   parade:"Ask yourself: “What could prove me WRONG?” — then really go and look for it."},
  {id:"halo",
   def:"A visible quality (beauty, talent, likeability) <b>spills over</b> onto everything else: we assume the person is competent or honest in every field.",
   ex:"A judo champion praises a car → people believe him, even though he knows nothing about mechanics.",
   parade:"Separate the person from the message: “are they truly competent on THIS precise topic?”"},
  {id:"emo",
   def:"Information that <b>moves</b> us (fear, anger, tenderness) grabs attention and gets shared more — whether true or false.",
   ex:"An AI-generated photo of a child in ruins gets millions of shares.",
   parade:"If information makes you react strongly, be careful: it is often designed to do exactly that. Breathe before sharing."},
  {id:"popu",
   def:"We believe something is true or good <b>because many people</b> support it (social proof).",
   ex:"“Millions of people use this tip, so it must work!”",
   parade:"Numbers prove nothing: millions of people have been wrong together before. Look for evidence, not numbers."},
  {id:"heur",
   def:"A <b>mental shortcut</b>: we conclude quickly from the first thing that comes to mind, without checking everything.",
   ex:"A speaker talks well and was invited by the school → we assume he is an expert, without checking.",
   parade:"Ask yourself: “Where did I get what I believe?” And slow down on topics that matter."},
  {id:"surv",
   def:"We only look at those who <b>“survived”/succeeded</b>, forgetting all the invisible cases that failed.",
   ex:"People want to reinforce planes where the returning planes were hit… when they should reinforce where the downed planes were hit.",
   parade:"Ask: “Who is missing from the picture? Who could not come back to testify?”"},
  {id:"cadr",
   def:"The <b>same information</b> changes meaning depending on how it is presented.",
   ex:"“64% keep their budget” vs “1 in 3 must reduce it”: same figure, opposite feeling.",
   parade:"Rephrase the information the other way around (glass half full / half empty) to see the chosen angle."},
  {id:"ancr",
   def:"The <b>first number or first idea</b> encountered becomes a reference point and influences all our later judgments.",
   ex:"A very high crossed-out price makes the “sale” price look attractive, even if it is still expensive.",
   parade:"Ignore the reference point imposed on you: look for a neutral, independent reference."},
  {id:"auto",
   def:"We believe or obey because something comes from an <b>authority figure</b> (title, lab coat, uniform), without checking.",
   ex:"“Recommended by dentists” convinces us to buy, without any evidence.",
   parade:"An authority can be wrong or speak outside their field. Ask for proof, not the title."},
  {id:"disp",
   def:"We judge an event to be <b>frequent</b> simply because it comes easily to mind (seen in the news, striking).",
   ex:"After a report about a crash, we fear flying — even though cars kill far more people.",
   parade:"Look for the real figures, not the most striking examples in your memory."},
  {id:"caus",
   def:"Two things that vary <b>together</b> do not necessarily explain each other.",
   ex:"Ice-cream sales and drownings rise together… because of summer, not because one causes the other.",
   parade:"Ask: “Is there a 3rd common cause? Or is it just coincidence?”"},
  {id:"nega",
   def:"The <b>negative</b> (danger, drama, criticism) grabs more attention and leaves a stronger mark than the positive.",
   ex:"The news strings together disasters → we end up believing “everything is getting worse”.",
   parade:"For every bad news story, look for context and background data before concluding."},
  {id:"retro",
   def:"Once the result is known, we are convinced we <b>“knew it all along”</b>: it was obvious… after the fact.",
   ex:"After a crash: “It was obvious it would collapse!” — even though nobody had predicted it.",
   parade:"Write down your predictions BEFORE: you will see that the future was much less obvious than it seems."},
  {id:"barn",
   def:"We take personally a <b>profile vague enough</b> to apply to almost everyone.",
   ex:"“You are sociable but sometimes reserved”: the horoscope or test that “gets it right”… for everyone.",
   parade:"Ask: “Could this description fit almost anyone?”"},
];

function renderFiches(){
  const g=$("fiches-grid");if(!g||g.childElementCount)return;
  FICHES.forEach(f=>{
    const title=f.concept?(f.icon+" "+f.title):BIAS[f.id].l;
    const d=document.createElement("div");
    d.className="fiche"+(f.concept?" concept":"");
    d.innerHTML=`<h3>${title}</h3>`+
      `<p class="f-def">${f.def}</p>`+
      `<p class="f-ex"><span class="f-lab">Example</span>${f.ex}</p>`+
      `<div class="f-parade"><span class="f-lab">The reflex</span>${f.parade}</div>`;
    g.appendChild(d);
  });
}
function showFiches(){
  renderFiches();
  $("intro").style.display="none";
  $("fiches").style.display="block";
  window.scrollTo({top:0,behavior:"smooth"});
}
function hideFiches(){
  $("fiches").style.display="none";
  $("intro").style.display="block";
  window.scrollTo({top:0,behavior:"smooth"});
}
